name: Trigger auto deployment for container-app-nka773emi3pmm

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'application/**'
    - '.github/workflows/container-app-nka773emi3pmm-AutoDeployTrigger-c2387a7a-ed4a-4a97-b1f6-a8f1c7606fe2.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPNKA773EMI3PMM_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPNKA773EMI3PMM_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPNKA773EMI3PMM_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/application 
          registryUrl: containerregistrynka773emi3pmm.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPNKA773EMI3PMM_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPNKA773EMI3PMM_REGISTRY_PASSWORD }}
          containerAppName: container-app-nka773emi3pmm
          resourceGroup: dotnetcorecontainerizedsqldbghactionsa749
          imageToBuild: containerregistrynka773emi3pmm.azurecr.io/container-app-nka773emi3pmm:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


